// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[convoId].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/api/[deploymentId]/conversations/[convoId].ts";
import * as $4 from "./routes/api/embeddings/files.ts";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/test.tsx";
import * as $$0 from "./islands/Breadcrumb.tsx";
import * as $$1 from "./islands/ChatBox.tsx";
import * as $$2 from "./islands/ChatHistory.tsx";
import * as $$3 from "./islands/Counter.tsx";
import * as $$4 from "./islands/DropDownButton.jsx";
import * as $$5 from "./islands/NavBar.tsx";
import * as $$6 from "./islands/NavBarHarbor.tsx";
import * as $$7 from "./islands/PieChart.tsx";
import * as $$8 from "./islands/TextStream.tsx";
import * as $$9 from "./islands/chart.tsx";

const manifest = {
  routes: {
    "./routes/[convoId].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/api/[deploymentId]/conversations/[convoId].ts": $3,
    "./routes/api/embeddings/files.ts": $4,
    "./routes/index.tsx": $5,
    "./routes/test.tsx": $6,
  },
  islands: {
    "./islands/Breadcrumb.tsx": $$0,
    "./islands/ChatBox.tsx": $$1,
    "./islands/ChatHistory.tsx": $$2,
    "./islands/Counter.tsx": $$3,
    "./islands/DropDownButton.jsx": $$4,
    "./islands/NavBar.tsx": $$5,
    "./islands/NavBarHarbor.tsx": $$6,
    "./islands/PieChart.tsx": $$7,
    "./islands/TextStream.tsx": $$8,
    "./islands/chart.tsx": $$9,
  },
  baseUrl: import.meta.url,
};

export default manifest;
