// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/embeddings/files.ts";
import * as $3 from "./routes/api/portrayals/[portrayalLookup].ts";
import * as $4 from "./routes/api/portrayals/index.ts";
import * as $5 from "./routes/api/portrayals/regenerate/[convoLookup].ts";
import * as $6 from "./routes/api/reports/[reportLookup].ts";
import * as $7 from "./routes/api/reports/index.ts";
import * as $8 from "./routes/dashboard/[convoLookup].tsx";
import * as $9 from "./routes/dashboard/_middleware.ts";
import * as $10 from "./routes/dashboard/index.tsx";
import * as $11 from "./routes/dashboard/new-conversation.tsx";
import * as $12 from "./routes/dashboard/portrayals/[portrayalLookup].tsx";
import * as $13 from "./routes/dashboard/portrayals/index.tsx";
import * as $14 from "./routes/dashboard/reports.tsx";
import * as $15 from "./routes/dashboard/reports/[reportLookup].tsx";
import * as $16 from "./routes/dashboard/reports/index.tsx";
import * as $17 from "./routes/dashboard/reports/new.tsx";
import * as $18 from "./routes/dashboard/signout.tsx";
import * as $19 from "./routes/index.tsx";
import * as $$0 from "./islands/Breadcrumb.tsx";
import * as $$1 from "./islands/ChartIsland.tsx";
import * as $$2 from "./islands/ChatHistory.tsx";
import * as $$3 from "./islands/ConvoItem.tsx";
import * as $$4 from "./islands/DropDownButton.jsx";
import * as $$5 from "./islands/FileUploader.tsx";
import * as $$6 from "./islands/NavBar.tsx";
import * as $$7 from "./islands/NavBarBranded.tsx";
import * as $$8 from "./islands/PortrayalForm.tsx";
import * as $$9 from "./islands/PortrayalItem.tsx";
import * as $$10 from "./islands/ReportItem.tsx";
import * as $$11 from "./islands/_islands.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/embeddings/files.ts": $2,
    "./routes/api/portrayals/[portrayalLookup].ts": $3,
    "./routes/api/portrayals/index.ts": $4,
    "./routes/api/portrayals/regenerate/[convoLookup].ts": $5,
    "./routes/api/reports/[reportLookup].ts": $6,
    "./routes/api/reports/index.ts": $7,
    "./routes/dashboard/[convoLookup].tsx": $8,
    "./routes/dashboard/_middleware.ts": $9,
    "./routes/dashboard/index.tsx": $10,
    "./routes/dashboard/new-conversation.tsx": $11,
    "./routes/dashboard/portrayals/[portrayalLookup].tsx": $12,
    "./routes/dashboard/portrayals/index.tsx": $13,
    "./routes/dashboard/reports.tsx": $14,
    "./routes/dashboard/reports/[reportLookup].tsx": $15,
    "./routes/dashboard/reports/index.tsx": $16,
    "./routes/dashboard/reports/new.tsx": $17,
    "./routes/dashboard/signout.tsx": $18,
    "./routes/index.tsx": $19,
  },
  islands: {
    "./islands/Breadcrumb.tsx": $$0,
    "./islands/ChartIsland.tsx": $$1,
    "./islands/ChatHistory.tsx": $$2,
    "./islands/ConvoItem.tsx": $$3,
    "./islands/DropDownButton.jsx": $$4,
    "./islands/FileUploader.tsx": $$5,
    "./islands/NavBar.tsx": $$6,
    "./islands/NavBarBranded.tsx": $$7,
    "./islands/PortrayalForm.tsx": $$8,
    "./islands/PortrayalItem.tsx": $$9,
    "./islands/ReportItem.tsx": $$10,
    "./islands/_islands.tsx": $$11,
  },
  baseUrl: import.meta.url,
};

export default manifest;
