# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - community-chat

on:
  push:
    branches:
      - integration
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://fathymcloudprd.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_fc2f0235d1b046638c35a9a969e8a5dc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_232d98e60b7d4ecabf61da177a5712dd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        build-args: GIT_REVISION=${{ github.sha }}
        push: true
        tags: fathymcloudprd.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fc2f0235d1b046638c35a9a969e8a5dc }}/community-chat:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'community-chat'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_490a3ccae38346c19f3fe054ae9d4e8a }}
        images: 'fathymcloudprd.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fc2f0235d1b046638c35a9a969e8a5dc }}/community-chat:${{ github.sha }}'